name: CI
run-name: ${{ github.actor }} is testing the context
on: push
jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "developing to production server on branch $GITHUB_REF"